import { LibraryDocument } from '@/types/library'

export const mockLibraryDocuments: LibraryDocument[] = [
  {
    id: 'doc-001',
    name: 'Master Service Agreement',
    description: 'Standard master service agreement for all supplier contracts',
    category: 'Legal',
    fileType: 'PDF',
    fileSize: 245000,
    uploadedAt: '2024-01-15T10:30:00Z',
    uploadedBy: 'John Smith',
    tags: ['contract', 'legal', 'msa', 'standard'],
    usedInRFPs: ['rfp-001', 'rfp-003', 'rfp-005'],
    version: '2.1',
  },
  {
    id: 'doc-002',
    name: 'Supplier Questionnaire Template',
    description: 'Comprehensive questionnaire for supplier capability assessment',
    category: 'Forms',
    fileType: 'DOCX',
    fileSize: 156000,
    uploadedAt: '2024-01-10T14:20:00Z',
    uploadedBy: 'Sarah Johnson',
    tags: ['questionnaire', 'evaluation', 'supplier', 'form'],
    usedInRFPs: ['rfp-001', 'rfp-002', 'rfp-004'],
    version: '1.5',
  },
  {
    id: 'doc-003',
    name: 'Compliance Requirements Checklist',
    description: 'Required compliance certifications and standards',
    category: 'Guidelines',
    fileType: 'PDF',
    fileSize: 89000,
    uploadedAt: '2024-01-12T09:15:00Z',
    uploadedBy: 'Mike Chen',
    tags: ['compliance', 'requirements', 'certification', 'iso'],
    usedInRFPs: ['rfp-002', 'rfp-003'],
    version: '1.2',
  },
  {
    id: 'doc-004',
    name: 'Sustainability & ESG Policy',
    description: 'Company sustainability requirements and ESG criteria for suppliers',
    category: 'Policies',
    fileType: 'PDF',
    fileSize: 234000,
    uploadedAt: '2024-01-08T11:45:00Z',
    uploadedBy: 'Lisa Martinez',
    tags: ['sustainability', 'esg', 'environment', 'policy'],
    usedInRFPs: ['rfp-001', 'rfp-003', 'rfp-004', 'rfp-005'],
    version: '3.0',
  },
  {
    id: 'doc-005',
    name: 'Data Security & Privacy Requirements',
    description: 'GDPR compliance and data security standards for all suppliers',
    category: 'Legal',
    fileType: 'PDF',
    fileSize: 178000,
    uploadedAt: '2024-01-05T13:20:00Z',
    uploadedBy: 'Tom Wilson',
    tags: ['data', 'security', 'privacy', 'gdpr', 'compliance'],
    usedInRFPs: ['rfp-002', 'rfp-005'],
    version: '1.8',
  },
  {
    id: 'doc-006',
    name: 'RFP Response Template',
    description: 'Template for suppliers to use when responding to RFP',
    category: 'Template',
    fileType: 'DOCX',
    fileSize: 267000,
    uploadedAt: '2024-01-03T10:00:00Z',
    uploadedBy: 'Sarah Johnson',
    tags: ['template', 'rfp', 'response', 'proposal'],
    usedInRFPs: ['rfp-001', 'rfp-002', 'rfp-003', 'rfp-004'],
    version: '2.2',
  },
  {
    id: 'doc-007',
    name: 'Pricing Schedule Template',
    description: 'Standard pricing and cost breakdown template',
    category: 'Template',
    fileType: 'XLSX',
    fileSize: 45000,
    uploadedAt: '2024-01-02T15:30:00Z',
    uploadedBy: 'Emma Davis',
    tags: ['pricing', 'cost', 'template', 'excel'],
    usedInRFPs: ['rfp-003', 'rfp-004', 'rfp-005'],
    version: '1.0',
  },
  {
    id: 'doc-008',
    name: 'Company Background & History',
    description: 'Company overview, history, and organizational structure',
    category: 'General',
    fileType: 'PDF',
    fileSize: 156000,
    uploadedAt: '2024-01-01T09:00:00Z',
    uploadedBy: 'John Smith',
    tags: ['company', 'overview', 'background'],
    usedInRFPs: [],
    version: '1.0',
  },
  {
    id: 'doc-009',
    name: 'Technical Specifications - Cloud Services',
    description: 'Technical requirements and specifications for cloud service providers',
    category: 'Data',
    fileType: 'PDF',
    fileSize: 289000,
    uploadedAt: '2023-12-28T14:15:00Z',
    uploadedBy: 'Alex Kumar',
    tags: ['technical', 'cloud', 'specifications', 'requirements'],
    usedInRFPs: ['rfp-002'],
    version: '2.1',
  },
  {
    id: 'doc-010',
    name: 'Case Study - Previous Successful Project',
    description: 'Example case study from previous successful supplier engagement',
    category: 'Examples',
    fileType: 'PDF',
    fileSize: 198000,
    uploadedAt: '2023-12-25T11:30:00Z',
    uploadedBy: 'Rachel Green',
    tags: ['case study', 'example', 'project', 'success'],
    usedInRFPs: ['rfp-004'],
    version: '1.0',
  },
]
