import { Supplier } from '@/types/supplier'

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-001',
    name: 'EcoMetrics Advisory',
    tier: 'preferred',
    expertise: [
      'Scope 3 / Value Chain',
      'Carbon Accounting',
      'ESG Reporting',
      'Data Analytics',
    ],
    totalContractValue: 1250000,
    contractsWon: 8,
    contractsLost: 2,
    lastContacted: '2025-04-28',
    companyContact: {
      email: 'contact@ecometrics.com',
      phone: '+1 (555) 123-4567',
      address: '123 Sustainability Ave, San Francisco, CA 94105',
    },
    teamMembers: [
      {
        id: 'tm-001',
        name: 'Dr. Sarah Chen',
        title: 'Director of Emissions',
        function: 'Technical Lead',
        email: 'sarah.chen@ecometrics.com',
        phone: '+1 (555) 123-4568',
        proposalsWon: 6,
        proposalsLost: 1,
        relatedRFPs: ['rfp-001', 'rfp-002', 'rfp-003'],
      },
      {
        id: 'tm-002',
        name: 'Marcus Johnson',
        title: 'Senior Carbon Analyst',
        function: 'Account Manager',
        email: 'marcus.johnson@ecometrics.com',
        phone: '+1 (555) 123-4569',
        proposalsWon: 2,
        proposalsLost: 1,
        relatedRFPs: ['rfp-001', 'rfp-004'],
      },
    ],
    engagementHistory: [
      {
        id: 'eng-001',
        date: '2025-04-28',
        type: 'email',
        notes: 'Discussed Scope 3 methodology and baseline year selection',
        relatedRFP: 'rfp-001',
      },
      {
        id: 'eng-002',
        date: '2025-04-15',
        type: 'meeting',
        notes: 'Quarterly business review on emissions reporting',
      },
    ],
    createdAt: '2024-01-15',
    updatedAt: '2025-04-28',
  },
  {
    id: 'sup-002',
    name: 'CarbonClear Solutions',
    tier: 'preferred',
    expertise: [
      'Target Setting (SBTi)',
      'Regulatory Reporting (ISSB/CSRD)',
      'Financed Emissions (PCAF/SFDR)',
      'ESG Reporting',
    ],
    totalContractValue: 890000,
    contractsWon: 5,
    contractsLost: 1,
    lastContacted: '2025-04-20',
    companyContact: {
      email: 'info@carbonclear.com',
      phone: '+1 (555) 234-5678',
      address: '456 Climate Lane, Boston, MA 02101',
    },
    teamMembers: [
      {
        id: 'tm-003',
        name: 'Emily Rodriguez',
        title: 'SBTi Specialist',
        function: 'Project Manager',
        email: 'emily.rodriguez@carbonclear.com',
        phone: '+1 (555) 234-5679',
        proposalsWon: 5,
        proposalsLost: 1,
        relatedRFPs: ['rfp-002', 'rfp-005'],
      },
    ],
    engagementHistory: [
      {
        id: 'eng-003',
        date: '2025-04-20',
        type: 'call',
        notes: 'Discussed SBTi validation timeline and ISSB reporting requirements',
      },
    ],
    createdAt: '2024-02-20',
    updatedAt: '2025-04-20',
  },
  {
    id: 'sup-003',
    name: 'Transition Risk Partners',
    tier: 'standard',
    expertise: [
      'Life Cycle Assessment (LCA)',
      'Environmental Impact (EIA)',
      'Regulatory Reporting (ISSB/CSRD)',
      'Data Analytics',
    ],
    totalContractValue: 560000,
    contractsWon: 3,
    contractsLost: 2,
    lastContacted: '2025-04-10',
    companyContact: {
      email: 'sales@transitionrisk.com',
      phone: '+1 (555) 345-6789',
      address: '789 ESG Road, Austin, TX 78701',
    },
    teamMembers: [
      {
        id: 'tm-004',
        name: 'Robert Williams',
        title: 'VP Climate Risk Assessment',
        function: 'Business Development',
        email: 'robert.williams@transitionrisk.com',
        phone: '+1 (555) 345-6790',
        proposalsWon: 2,
        proposalsLost: 1,
        relatedRFPs: ['rfp-001'],
      },
      {
        id: 'tm-005',
        name: 'Lisa Anderson',
        title: 'LCA Specialist',
        function: 'Technical Consultant',
        email: 'lisa.anderson@transitionrisk.com',
        phone: '+1 (555) 345-6791',
        proposalsWon: 1,
        proposalsLost: 1,
        relatedRFPs: ['rfp-006'],
      },
    ],
    engagementHistory: [
      {
        id: 'eng-004',
        date: '2025-04-10',
        type: 'note',
        notes: 'Follow-up needed for LCA project scope refinement',
      },
    ],
    createdAt: '2024-03-10',
    updatedAt: '2025-04-10',
  },
  {
    id: 'sup-004',
    name: 'SustainSustain',
    tier: 'standard',
    expertise: [
      'Renewable Energy (PPA/VPPA)',
      'Certifications (ISO/LEED)',
      'Energy Efficiency',
      'Environmental Compliance',
    ],
    totalContractValue: 420000,
    contractsWon: 2,
    contractsLost: 3,
    lastContacted: '2025-03-25',
    companyContact: {
      email: 'contact@sustainsustain.io',
      phone: '+1 (555) 456-7890',
      address: '321 Renewable Way, Boulder, CO 80302',
    },
    teamMembers: [
      {
        id: 'tm-006',
        name: 'David Park',
        title: 'Renewable Energy Manager',
        function: 'Project Lead',
        email: 'david.park@sustainsustain.io',
        phone: '+1 (555) 456-7891',
        proposalsWon: 2,
        proposalsLost: 2,
        relatedRFPs: ['rfp-004', 'rfp-005'],
      },
    ],
    engagementHistory: [
      {
        id: 'eng-005',
        date: '2025-03-25',
        type: 'email',
        notes: 'Submitted proposal for VPPA structuring and renewable energy procurement',
        relatedRFP: 'rfp-005',
      },
    ],
    createdAt: '2024-01-05',
    updatedAt: '2025-03-25',
  },
  {
    id: 'sup-005',
    name: 'PCAF Analytics Group',
    tier: 'new',
    expertise: [
      'Financed Emissions (PCAF/SFDR)',
      'Financial Carbon Accounting',
      'Risk Assessment',
      'ESG Data',
    ],
    totalContractValue: 0,
    contractsWon: 0,
    contractsLost: 0,
    lastContacted: null,
    companyContact: {
      email: 'procurement@pcafgroup.com',
      phone: '+1 (555) 567-8901',
      address: '555 Finance Avenue, New York, NY 10001',
    },
    teamMembers: [
      {
        id: 'tm-007',
        name: 'James Mitchell',
        title: 'Financial Climate Officer',
        function: 'Sales Director',
        email: 'james.mitchell@pcafgroup.com',
        phone: '+1 (555) 567-8902',
        proposalsWon: 0,
        proposalsLost: 0,
        relatedRFPs: [],
      },
    ],
    engagementHistory: [],
    createdAt: '2025-04-01',
    updatedAt: '2025-04-01',
  },
  {
    id: 'sup-006',
    name: 'Lifecycle Data Labs',
    tier: 'standard',
    expertise: [
      'Life Cycle Assessment (LCA)',
      'Embodied Carbon',
      'Material Science',
      'Environmental Analysis',
    ],
    totalContractValue: 280000,
    contractsWon: 1,
    contractsLost: 0,
    lastContacted: '2025-04-05',
    companyContact: {
      email: 'contact@lifecycledata.com',
      phone: '+1 (555) 678-9012',
      address: '777 Science Park, Cambridge, MA 02138',
    },
    teamMembers: [
      {
        id: 'tm-008',
        name: 'Dr. Patricia Smith',
        title: 'Principal LCA Researcher',
        function: 'Project Lead',
        email: 'patricia.smith@lifecycledata.com',
        phone: '+1 (555) 678-9013',
        proposalsWon: 1,
        proposalsLost: 0,
        relatedRFPs: ['rfp-003'],
      },
    ],
    engagementHistory: [
      {
        id: 'eng-006',
        date: '2025-04-05',
        type: 'meeting',
        notes: 'Completed baseline LCA study for commercial real estate project',
      },
    ],
    createdAt: '2024-06-15',
    updatedAt: '2025-04-05',
  },
]
