import { LibraryDocument } from '@/types/library'

export const mockLibraryDocuments: LibraryDocument[] = [
  {
    id: 'doc-001',
    name: 'Corporate Sustainability Policy',
    description: 'Company-wide sustainability commitments and climate goals including net-zero targets and science-based targets alignment',
    category: 'Policies',
    fileType: 'PDF',
    fileSize: 245000,
    uploadedAt: '2024-01-15T10:30:00Z',
    uploadedBy: 'Emma Thompson',
    tags: ['sustainability', 'policy', 'climate', 'net-zero', 'sbti'],
    usedInRFPs: ['rfp-001', 'rfp-003', 'rfp-005'],
    version: '2.1',
  },
  {
    id: 'doc-002',
    name: 'ESG Disclosure Questionnaire',
    description: 'Comprehensive supplier ESG assessment form covering emissions, governance, labor practices, and supply chain transparency',
    category: 'Forms',
    fileType: 'DOCX',
    fileSize: 156000,
    uploadedAt: '2024-01-10T14:20:00Z',
    uploadedBy: 'David Kumar',
    tags: ['esg', 'questionnaire', 'assessment', 'supplier', 'form'],
    usedInRFPs: ['rfp-001', 'rfp-002', 'rfp-004'],
    version: '1.5',
  },
  {
    id: 'doc-003',
    name: 'Scope 3 Emissions Methodology Guide',
    description: 'Technical guidelines for calculating and reporting Scope 3 emissions across all 15 categories per GHG Protocol',
    category: 'Guidelines',
    fileType: 'PDF',
    fileSize: 89000,
    uploadedAt: '2024-01-12T09:15:00Z',
    uploadedBy: 'Michael Chen',
    tags: ['scope-3', 'emissions', 'methodology', 'ghg-protocol', 'carbon'],
    usedInRFPs: ['rfp-002', 'rfp-003'],
    version: '1.2',
  },
  {
    id: 'doc-004',
    name: 'ISSB & CSRD Compliance Requirements',
    description: 'Regulatory reporting standards for IFRS Sustainability Standards (ISSB) and Corporate Sustainability Reporting Directive (CSRD)',
    category: 'Legal',
    fileType: 'PDF',
    fileSize: 234000,
    uploadedAt: '2024-01-08T11:45:00Z',
    uploadedBy: 'Lisa Martinez',
    tags: ['issb', 'csrd', 'regulatory', 'compliance', 'sustainability'],
    usedInRFPs: ['rfp-001', 'rfp-003', 'rfp-004', 'rfp-005'],
    version: '3.0',
  },
  {
    id: 'doc-005',
    name: 'SBTi Target Validation Process',
    description: 'Step-by-step guide for developing and validating science-based targets aligned with 1.5°C climate scenarios',
    category: 'Guidelines',
    fileType: 'PDF',
    fileSize: 178000,
    uploadedAt: '2024-01-05T13:20:00Z',
    uploadedBy: 'Tom Wilson',
    tags: ['sbti', 'targets', 'science-based', 'climate', 'validation'],
    usedInRFPs: ['rfp-002', 'rfp-005'],
    version: '1.8',
  },
  {
    id: 'doc-006',
    name: 'RFP Response Template - Sustainability Focus',
    description: 'Template for suppliers to respond to sustainability RFPs with required ESG data and commitments',
    category: 'Template',
    fileType: 'DOCX',
    fileSize: 267000,
    uploadedAt: '2024-01-03T10:00:00Z',
    uploadedBy: 'Rachel Green',
    tags: ['template', 'rfp', 'response', 'sustainability', 'esg'],
    usedInRFPs: ['rfp-001', 'rfp-002', 'rfp-003', 'rfp-004'],
    version: '2.2',
  },
  {
    id: 'doc-007',
    name: 'Life Cycle Assessment Framework',
    description: 'LCA methodology for evaluating environmental impacts of products and services from cradle-to-grave',
    category: 'Guidelines',
    fileType: 'PDF',
    fileSize: 312000,
    uploadedAt: '2024-01-02T15:30:00Z',
    uploadedBy: 'Dr. Patricia Smith',
    tags: ['lca', 'lifecycle-assessment', 'environmental-impact', 'cradle-to-grave'],
    usedInRFPs: ['rfp-003', 'rfp-004', 'rfp-006'],
    version: '1.0',
  },
  {
    id: 'doc-008',
    name: 'PCAF Financed Emissions Guidance',
    description: 'Partnership for Carbon Accounting Financials methodology for calculating emissions from investment portfolios',
    category: 'Data',
    fileType: 'PDF',
    fileSize: 245000,
    uploadedAt: '2024-01-01T09:00:00Z',
    uploadedBy: 'John Smith',
    tags: ['pcaf', 'financed-emissions', 'finance', 'carbon-accounting'],
    usedInRFPs: [],
    version: '1.0',
  },
  {
    id: 'doc-009',
    name: 'Renewable Energy Procurement Standards',
    description: 'Requirements and evaluation criteria for renewable energy and Virtual Power Purchase Agreement (VPPA) structuring',
    category: 'Guidelines',
    fileType: 'PDF',
    fileSize: 289000,
    uploadedAt: '2023-12-28T14:15:00Z',
    uploadedBy: 'Alex Kumar',
    tags: ['renewable-energy', 'vppa', 'procurement', 'energy-standards'],
    usedInRFPs: ['rfp-002', 'rfp-007'],
    version: '2.1',
  },
  {
    id: 'doc-010',
    name: 'Case Study - Scope 3 Reduction Success',
    description: 'Real-world example of how a peer company successfully identified and reduced 28% of Scope 3 emissions',
    category: 'Examples',
    fileType: 'PDF',
    fileSize: 198000,
    uploadedAt: '2023-12-25T11:30:00Z',
    uploadedBy: 'Emma Thompson',
    tags: ['case-study', 'example', 'scope-3', 'emissions-reduction'],
    usedInRFPs: ['rfp-001'],
    version: '1.0',
  },
]
