import { Supplier } from '@/types/supplier'

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-001',
    name: 'GreenTech Solutions',
    tier: 'preferred',
    expertise: [
      'Cloud Infrastructure',
      'Renewable Energy',
      'ESG Reporting',
      'Data Analytics',
    ],
    totalContractValue: 1250000,
    contractsWon: 8,
    contractsLost: 2,
    lastContacted: '2025-04-28',
    companyContact: {
      email: 'contact@greentech.com',
      phone: '+1 (555) 123-4567',
      address: '123 Eco Drive, San Francisco, CA 94105',
    },
    teamMembers: [
      {
        id: 'tm-001',
        name: 'Sarah Chen',
        title: 'Solutions Architect',
        function: 'Account Manager',
        email: 'sarah.chen@greentech.com',
        phone: '+1 (555) 123-4568',
        proposalsWon: 6,
        proposalsLost: 1,
        relatedRFPs: ['rfp-001', 'rfp-002', 'rfp-003'],
      },
      {
        id: 'tm-002',
        name: 'Marcus Johnson',
        title: 'Senior Consultant',
        function: 'Technical Lead',
        email: 'marcus.johnson@greentech.com',
        phone: '+1 (555) 123-4569',
        proposalsWon: 2,
        proposalsLost: 1,
        relatedRFPs: ['rfp-001', 'rfp-004'],
      },
    ],
    engagementHistory: [
      {
        id: 'eng-001',
        date: '2025-04-28',
        type: 'email',
        notes: 'Discussed Q3 renewable energy project',
        relatedRFP: 'rfp-003',
      },
      {
        id: 'eng-002',
        date: '2025-04-15',
        type: 'meeting',
        notes: 'Quarterly business review',
      },
    ],
    createdAt: '2024-01-15',
    updatedAt: '2025-04-28',
  },
  {
    id: 'sup-002',
    name: 'SustainCorp Consulting',
    tier: 'preferred',
    expertise: [
      'Sustainability Consulting',
      'Environmental Compliance',
      'Carbon Accounting',
      'ESG Reporting',
    ],
    totalContractValue: 890000,
    contractsWon: 5,
    contractsLost: 1,
    lastContacted: '2025-04-20',
    companyContact: {
      email: 'info@sustaincorp.com',
      phone: '+1 (555) 234-5678',
      address: '456 Green Lane, Boston, MA 02101',
    },
    teamMembers: [
      {
        id: 'tm-003',
        name: 'Emily Rodriguez',
        title: 'Sustainability Director',
        function: 'Project Manager',
        email: 'emily.rodriguez@sustaincorp.com',
        phone: '+1 (555) 234-5679',
        proposalsWon: 5,
        proposalsLost: 1,
        relatedRFPs: ['rfp-002', 'rfp-005'],
      },
    ],
    engagementHistory: [
      {
        id: 'eng-003',
        date: '2025-04-20',
        type: 'call',
        notes: 'Discussed compliance requirements for new initiative',
      },
    ],
    createdAt: '2024-02-20',
    updatedAt: '2025-04-20',
  },
  {
    id: 'sup-003',
    name: 'LogiServe Global',
    tier: 'standard',
    expertise: [
      'Logistics & Transportation',
      'Supply Chain Management',
      'Warehouse Solutions',
      'Data Analytics',
    ],
    totalContractValue: 560000,
    contractsWon: 3,
    contractsLost: 2,
    lastContacted: '2025-04-10',
    companyContact: {
      email: 'sales@logiserve.com',
      phone: '+1 (555) 345-6789',
      address: '789 Trade Road, Atlanta, GA 30303',
    },
    teamMembers: [
      {
        id: 'tm-004',
        name: 'Robert Williams',
        title: 'VP Sales',
        function: 'Business Development',
        email: 'robert.williams@logiserve.com',
        phone: '+1 (555) 345-6790',
        proposalsWon: 2,
        proposalsLost: 1,
        relatedRFPs: ['rfp-001'],
      },
      {
        id: 'tm-005',
        name: 'Lisa Anderson',
        title: 'Operations Manager',
        function: 'Operations',
        email: 'lisa.anderson@logiserve.com',
        phone: '+1 (555) 345-6791',
        proposalsWon: 1,
        proposalsLost: 1,
        relatedRFPs: ['rfp-006'],
      },
    ],
    engagementHistory: [
      {
        id: 'eng-004',
        date: '2025-04-10',
        type: 'note',
        notes: 'Follow-up needed for logistics RFP',
      },
    ],
    createdAt: '2024-03-10',
    updatedAt: '2025-04-10',
  },
  {
    id: 'sup-004',
    name: 'TechVenture Systems',
    tier: 'standard',
    expertise: [
      'Software/SaaS',
      'AI/Machine Learning',
      'IT Solutions',
      'Cybersecurity',
    ],
    totalContractValue: 420000,
    contractsWon: 2,
    contractsLost: 3,
    lastContacted: '2025-03-25',
    companyContact: {
      email: 'contact@techventure.io',
      phone: '+1 (555) 456-7890',
      address: '321 Silicon Valley, Mountain View, CA 94040',
    },
    teamMembers: [
      {
        id: 'tm-006',
        name: 'David Park',
        title: 'Sales Engineer',
        function: 'Account Executive',
        email: 'david.park@techventure.io',
        phone: '+1 (555) 456-7891',
        proposalsWon: 2,
        proposalsLost: 2,
        relatedRFPs: ['rfp-004', 'rfp-005'],
      },
    ],
    engagementHistory: [
      {
        id: 'eng-005',
        date: '2025-03-25',
        type: 'email',
        notes: 'Sent proposal for AI integration project',
        relatedRFP: 'rfp-005',
      },
    ],
    createdAt: '2024-01-05',
    updatedAt: '2025-03-25',
  },
  {
    id: 'sup-005',
    name: 'ProManufacture Inc',
    tier: 'new',
    expertise: [
      'Product Manufacturing',
      'Quality Assurance',
      'Manufacturing',
      'Packaging Solutions',
    ],
    totalContractValue: 0,
    contractsWon: 0,
    contractsLost: 0,
    lastContacted: null,
    companyContact: {
      email: 'procurement@promanufacture.com',
      phone: '+1 (555) 567-8901',
      address: '555 Factory Lane, Detroit, MI 48201',
    },
    teamMembers: [
      {
        id: 'tm-007',
        name: 'James Mitchell',
        title: 'Business Development Manager',
        function: 'Sales',
        email: 'james.mitchell@promanufacture.com',
        phone: '+1 (555) 567-8902',
        proposalsWon: 0,
        proposalsLost: 0,
        relatedRFPs: [],
      },
    ],
    engagementHistory: [],
    createdAt: '2025-04-01',
    updatedAt: '2025-04-01',
  },
  {
    id: 'sup-006',
    name: 'AuditPro Services',
    tier: 'standard',
    expertise: ['Auditing', 'Environmental Compliance', 'Quality Assurance'],
    totalContractValue: 280000,
    contractsWon: 1,
    contractsLost: 0,
    lastContacted: '2025-04-05',
    companyContact: {
      email: 'audit@auditpro.com',
      phone: '+1 (555) 678-9012',
      address: '777 Compliance Blvd, Chicago, IL 60601',
    },
    teamMembers: [
      {
        id: 'tm-008',
        name: 'Patricia Smith',
        title: 'Senior Auditor',
        function: 'Audit Lead',
        email: 'patricia.smith@auditpro.com',
        phone: '+1 (555) 678-9013',
        proposalsWon: 1,
        proposalsLost: 0,
        relatedRFPs: ['rfp-002'],
      },
    ],
    engagementHistory: [
      {
        id: 'eng-006',
        date: '2025-04-05',
        type: 'meeting',
        notes: 'Completed annual audit',
      },
    ],
    createdAt: '2024-06-15',
    updatedAt: '2025-04-05',
  },
]
